name: Run Linter

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Install Pint
        run: composer install --dev

      - name: Run Pint
        run: composer run lint
        if: github.event_name == 'pull_request'

      - name: Run Pint
        run: composer run lint:fix
        if: github.event_name == 'push'

      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix Linting
        if: github.event_name == 'push'
